version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # build the application image
     - run: docker build -t rasmus-unity/nodejs-docker-webapp:$CIRCLE_BRANCH .

     # deploy the image
     #  - run: docker push company/app:$CIRCLE_BRANCH
