kind: Service
apiVersion: v1
metadata:
  labels:
    app: ville-nodejs-docker-webapp
  name: ville-nodejs-docker-webapp
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ville-nodejs-docker-webapp
